teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.3
    scale_linear_turbo:
      x: 0.75

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 1.0

    enable_button:  4 # Left upper
    enable_turbo_button: 6  # Left lower
